main: com.njdaeger.greenfieldcore.GreenfieldCore
version: ${project.version}
name: ${project.artifactId}
author: NJDaeger
api-version: 1.17
softdepend:
  - Vault
  - CoreProtect
  - AuthenticationHub
  - Vault
  - dynmap
  - Essentials
  - WorldEdit