main: com.njdaeger.greenfieldcore.GreenfieldCore
version: ${project.version}
name: ${project.artifactId}
author: NJDaeger
api-version: 1.13
depend:
  - WorldEdit
  - Vault
  - MCLink
  - CoPerms
  - dynmap
  - CoreProtect
  - Essentials