main: net.greenfieldmc.core.GreenfieldCore
version: ${project.version}
name: ${project.artifactId}
author: NJDaeger
api-version: 1.21
softdepend:
  - Vault
  - CoreProtect
  - AuthenticationHub
  - Vault
  - dynmap
  - Essentials
  - WorldEdit